# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 08:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aw_name', models.CharField(max_length=64, null=True, verbose_name='Artwork Name')),
                ('aw_img', models.ImageField(default='/static/images/profile-default.png', upload_to='artwork/1507795801.158476', verbose_name='Image')),
                ('aw_description', models.CharField(max_length=256, null=True, verbose_name='Description')),
                ('aw_location', models.CharField(max_length=32, null=True, verbose_name='Location')),
                ('aw_time', models.DateTimeField(verbose_name='Add Time')),
                ('aw_type', models.CharField(max_length=32, null=True, verbose_name='Type')),
                ('aw_genre', models.CharField(max_length=32, null=True, verbose_name='Genre')),
                ('aw_auctionStat', models.BooleanField(verbose_name='Auction Status')),
                ('aw_totalAward', models.FloatField(default=0.0, verbose_name='Total Award')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Artist Name')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ah_amount', models.FloatField(default=0.0, verbose_name='Auction Amount')),
                ('ah_aucTime', models.DateTimeField(verbose_name='Auction Time')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_originalPrice', models.FloatField(default=0.0, verbose_name='Original Price')),
                ('ar_time', models.DateTimeField(verbose_name='Auction Time')),
                ('ar_finalPrice', models.FloatField(null=True, verbose_name='Final Price')),
                ('ar_period', models.FloatField(null=True, verbose_name='Period')),
                ('aw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtGallery.ArtWork', verbose_name='Artwork Name')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=256, null=True, verbose_name='Comment Content')),
                ('comment_time', models.DateTimeField(verbose_name='Comment Time')),
                ('rating', models.FloatField(default=5.0, verbose_name='Rating')),
                ('reply_commentId', models.IntegerField(null=True)),
                ('aw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtGallery.ArtWork', verbose_name='Artwork Name')),
                ('commenter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Commenter Name')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(default='Illegal', max_length=32, verbose_name='Complaint Type')),
                ('complaint_content', models.CharField(max_length=256, null=True, verbose_name='Complaint Content')),
                ('complaint_time', models.DateTimeField(null=True, verbose_name='Complaint Time')),
                ('aw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtGallery.ArtWork', verbose_name='Artwork Name')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_time', models.DateTimeField(verbose_name='Favourite Time')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Artist Name')),
                ('aw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtGallery.ArtWork', verbose_name='Artwork Name')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_amount', models.FloatField(default=0.0, verbose_name='Reward Amount')),
                ('reward_time', models.DateTimeField(verbose_name='Reward Time')),
                ('aw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtGallery.ArtWork', verbose_name='Artwork Name')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=16, verbose_name='Password')),
                ('sex', models.BooleanField(verbose_name='Gender')),
                ('birthday', models.DateTimeField(null=True, verbose_name='Birthday')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('identity', models.BooleanField(verbose_name='Identity')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
            ],
        ),
        migrations.AddField(
            model_name='auctionhistory',
            name='ar_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtGallery.AuctionRecord', verbose_name='Auction Record ID'),
        ),
        migrations.AddField(
            model_name='auctionhistory',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
    ]
