# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='aw_img',
            field=models.ImageField(upload_to='uploaded_arts'),
        ),
    ]
