# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='aw_img',
            field=models.ImageField(default='/static/images/profile-default.png', upload_to='artwork/1507188102.791539'),
        ),
    ]
