# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGallery', '0002_auto_20170908_1208'),
        ('ArtGallery', '0002_auto_20171005_0721'),
    ]

    operations = [
    ]
