# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 00:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGallery', '0002_auto_20170908_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='aw_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtGallery.ArtWork', verbose_name='Artwork Name'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_content',
            field=models.CharField(max_length=256, null=True, verbose_name='Complaint Content'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_time',
            field=models.DateTimeField(null=True, verbose_name='Complaint Time'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(default='Illegal', max_length=32, verbose_name='Complaint Type'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
    ]
