# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGallery', '0002_auto_20171012_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionhistory',
            name='ah_remaining',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='aw_img',
            field=models.ImageField(default='/static/images/profile-default.png', upload_to='artwork/1507791554.950271'),
        ),
    ]
