# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 05:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGallery', '0003_auto_20170923_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateTimeField(null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='identity',
            field=models.BooleanField(verbose_name='Identity'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=16, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.BooleanField(verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Name'),
        ),
    ]
