# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGallery', '0003_auto_20171012_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='aw_img',
            field=models.ImageField(default='/static/images/profile-default.png', upload_to='artwork/1508219736.842826'),
        ),
    ]
