# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGallery', '0003_merge_20171011_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionrecord',
            name='ar_end_time',
            field=models.DateTimeField(default='2019-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='aw_img',
            field=models.ImageField(default='/static/images/profile-default.png', upload_to='artwork/1507722628.897565'),
        ),
    ]
