# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 07:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGallery', '0004_auto_20170928_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Artist Name'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='aw_auctionStat',
            field=models.BooleanField(verbose_name='Auction Status'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='aw_description',
            field=models.CharField(max_length=256, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='aw_genre',
            field=models.CharField(max_length=32, null=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='aw_img',
            field=models.ImageField(default='/static/images/profile-default.png', upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='aw_location',
            field=models.CharField(max_length=32, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='aw_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Artwork Name'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='aw_time',
            field=models.DateTimeField(verbose_name='Add Time'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='aw_totalAward',
            field=models.FloatField(default=0.0, verbose_name='Total Award'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='aw_type',
            field=models.CharField(max_length=32, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='auctionhistory',
            name='ah_amount',
            field=models.FloatField(default=0.0, verbose_name='Auction Amount'),
        ),
        migrations.AlterField(
            model_name='auctionhistory',
            name='ah_aucTime',
            field=models.DateTimeField(verbose_name='Auction Time'),
        ),
        migrations.AlterField(
            model_name='auctionhistory',
            name='ar_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtGallery.AuctionRecord', verbose_name='Auction Record ID'),
        ),
        migrations.AlterField(
            model_name='auctionhistory',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='auctionrecord',
            name='ar_finalPrice',
            field=models.FloatField(null=True, verbose_name='Final Price'),
        ),
        migrations.AlterField(
            model_name='auctionrecord',
            name='ar_originalPrice',
            field=models.FloatField(default=0.0, verbose_name='Original Price'),
        ),
        migrations.AlterField(
            model_name='auctionrecord',
            name='ar_time',
            field=models.DateTimeField(verbose_name='Auction Time'),
        ),
        migrations.AlterField(
            model_name='auctionrecord',
            name='aw_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtGallery.ArtWork', verbose_name='Artwork Name'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='aw_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtGallery.ArtWork', verbose_name='Artwork Name'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.CharField(max_length=256, null=True, verbose_name='Comment Content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(verbose_name='Comment Time'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Commenter Name'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.FloatField(default=5.0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='favoriterecord',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Artist Name'),
        ),
        migrations.AlterField(
            model_name='favoriterecord',
            name='aw_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtGallery.ArtWork', verbose_name='Artwork Name'),
        ),
        migrations.AlterField(
            model_name='favoriterecord',
            name='fav_time',
            field=models.DateTimeField(verbose_name='Favourite Time'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='aw_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtGallery.ArtWork', verbose_name='Artwork Name'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_amount',
            field=models.FloatField(default=0.0, verbose_name='Reward Amount'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_time',
            field=models.DateTimeField(verbose_name='Reward Time'),
        ),
    ]
