# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGallery', '0005_auto_20171015_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionrecord',
            name='ar_period',
        ),
        migrations.AddField(
            model_name='auctionrecord',
            name='ar_end_time',
            field=models.DateTimeField(null=True, verbose_name='Auction End Time'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='aw_img',
            field=models.ImageField(default='/static/images/profile-default.png', upload_to='./artwork/1508371985.311978', verbose_name='Image'),
        ),
    ]
