# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGallery', '0005_auto_20171020_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='aw_img',
            field=models.ImageField(default='/static/images/profile-default.png', upload_to='./artwork/1509014661.792587', verbose_name='Image'),
        ),
    ]
