# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGallery', '0006_auto_20170914_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='aw_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commenter_id',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='aw_img',
            field=models.ImageField(default='/static/images/profile-default.png', upload_to='artwork/1505395178.416513'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
