# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 03:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ArtGallery', '0012_auto_20170915_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=256, null=True)),
                ('comment_time', models.DateTimeField()),
                ('rating', models.FloatField(default=5.0)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.DateTimeField()),
                ('response_content', models.CharField(max_length=256, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive', to=settings.AUTH_USER_MODEL)),
                ('response_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtGallery.Comment')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='artwork',
            name='aw_img',
            field=models.ImageField(default='/static/images/profile-default.png', upload_to='artwork/1505444484.7515001'),
        ),
        migrations.AddField(
            model_name='comment',
            name='aw_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtGallery.ArtWork'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
