# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGallery', '0013_auto_20170915_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='aw_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commenter_id',
        ),
        migrations.RemoveField(
            model_name='response',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='response',
            name='response_id',
        ),
        migrations.RemoveField(
            model_name='response',
            name='sender',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='aw_img',
            field=models.ImageField(default='/static/images/profile-default.png', upload_to='artwork/1505469517.983645'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
