# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGallery', '0015_auto_20170915_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='aw_img',
            field=models.ImageField(default='/static/images/profile-default.png', upload_to='artwork/1505469628.167572'),
        ),
    ]
