# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aw_name', models.CharField(max_length=64, null=True)),
                ('aw_description', models.CharField(max_length=256, null=True)),
                ('aw_location', models.CharField(max_length=32, null=True)),
                ('aw_time', models.DateTimeField()),
                ('aw_type', models.CharField(max_length=32, null=True)),
                ('aw_genre', models.CharField(max_length=32, null=True)),
                ('aw_auctionStat', models.BooleanField()),
                ('aw_totalAward', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ah_amount', models.FloatField(default=0.0)),
                ('ah_aucTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AuctionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_originalPrice', models.FloatField(default=0.0)),
                ('ar_time', models.DateTimeField()),
                ('ar_finalPrice', models.FloatField(null=True)),
                ('aw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelleryWeb.ArtWork')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=256, null=True)),
                ('comment_time', models.DateTimeField()),
                ('rating', models.FloatField(default=5.0)),
                ('replay_commentId', models.IntegerField(null=True)),
                ('aw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelleryWeb.ArtWork')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(default='Illegal', max_length=32)),
                ('complaint_content', models.CharField(max_length=256, null=True)),
                ('complaint_time', models.DateTimeField()),
                ('aw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelleryWeb.ArtWork')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField()),
                ('receiver_id', models.IntegerField()),
                ('notifyType', models.CharField(max_length=32, null=True)),
                ('aw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelleryWeb.ArtWork')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_amount', models.FloatField(default=0.0)),
                ('reward_time', models.DateTimeField()),
                ('aw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelleryWeb.ArtWork')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('sex', models.BooleanField()),
                ('birthday', models.DateTimeField(null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('identity', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='reward',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelleryWeb.Users'),
        ),
        migrations.AddField(
            model_name='favoriterecord',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelleryWeb.Users'),
        ),
        migrations.AddField(
            model_name='favoriterecord',
            name='aw_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelleryWeb.ArtWork'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelleryWeb.Users'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelleryWeb.Users'),
        ),
        migrations.AddField(
            model_name='auctionhistory',
            name='ar_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelleryWeb.AuctionRecord'),
        ),
        migrations.AddField(
            model_name='auctionhistory',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelleryWeb.Users'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelleryWeb.Users'),
        ),
    ]
